name: Build and Test

on: 
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: windows-latest
    strategy: 
      matrix: 
        rust: [stable]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt

    - name: tests
      run: cargo test --all

    - name: fmt
      run: cargo fmt --all -- --check
      if: matrix.rust == 'stable'
